monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_input.usb-Elgato.*"
      },
      {
        node.name = "~alsa_output.usb-Elgato.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-on-idle = false
      }
    }
  }
]
